<?php

use CRM_Obiaareport_ExtensionUtil as E;

return [
  [
    'name' => 'ReportInstance_1',
    'entity' => 'ReportInstance',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'title' => E::ts('Business Anniversary report'),
        'report_id' => 'contact/detail',
        'permission' => 'view all contacts',
        'form_values' => [
          'entryURL' => 'https://bia1.mainstreetrm.com/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Foptions%2Frelative_date_filters&page=CiviCRM&action=add&reset=1&crmAngularModules=crmResource',
          'fields' => [
            'sort_name' => '1',
            'custom_14' => '1',
            'bia_anniversary_date' => '1',
          ],
          'sort_name_op' => 'has',
          'sort_name_value' => '',
          'source_op' => 'has',
          'source_value' => '',
          'id_min' => '',
          'id_max' => '',
          'id_op' => 'lte',
          'id_value' => '',
          'gender_id_op' => 'in',
          'gender_id_value' => [],
          'birth_date_relative' => '',
          'birth_date_from' => '',
          'birth_date_to' => '',
          'contact_type_op' => 'in',
          'contact_type_value' => [],
          'contact_sub_type_op' => 'in',
          'contact_sub_type_value' => [
            'Members_Businesses_',
          ],
          'created_date_relative' => '',
          'created_date_from' => '',
          'created_date_to' => '',
          'modified_date_relative' => '',
          'modified_date_from' => '',
          'modified_date_to' => '',
          'is_deceased_op' => 'eq',
          'is_deceased_value' => '0',
          'do_not_email_op' => 'eq',
          'do_not_email_value' => '',
          'do_not_phone_op' => 'eq',
          'do_not_phone_value' => '',
          'do_not_mail_op' => 'eq',
          'do_not_mail_value' => '',
          'do_not_sms_op' => 'eq',
          'do_not_sms_value' => '',
          'do_not_trade_op' => 'eq',
          'do_not_trade_value' => '',
          'is_opt_out_op' => 'eq',
          'is_opt_out_value' => '',
          'preferred_language_op' => 'in',
          'preferred_language_value' => [],
          'is_deleted_op' => 'eq',
          'is_deleted_value' => '0',
          'tagid_op' => 'in',
          'tagid_value' => [],
          'gid_op' => 'in',
          'gid_value' => [],
          'custom_31_op' => 'has',
          'custom_31_value' => '',
          'custom_35_op' => 'has',
          'custom_35_value' => '',
          'custom_36_op' => 'has',
          'custom_36_value' => '',
          'custom_37_op' => 'has',
          'custom_37_value' => '',
          'custom_42_op' => 'has',
          'custom_42_value' => '',
          'custom_41_op' => 'has',
          'custom_41_value' => '',
          'custom_32_op' => 'has',
          'custom_32_value' => '',
          'custom_33_op' => 'has',
          'custom_33_value' => '',
          'custom_7_op' => 'mhas',
          'custom_7_value' => [],
          'custom_8_op' => 'mhas',
          'custom_8_value' => [],
          'custom_9_op' => 'mhas',
          'custom_9_value' => [],
          'custom_103_op' => 'eq',
          'custom_103_value' => '',
          'custom_13_op' => 'in',
          'custom_13_value' => [],
          'custom_28_op' => 'eq',
          'custom_28_value' => '',
          'custom_77_op' => 'in',
          'custom_77_value' => [],
          'custom_59_op' => 'in',
          'custom_59_value' => [],
          'custom_60_op' => 'in',
          'custom_60_value' => [],
          'custom_61_op' => 'in',
          'custom_61_value' => [],
          'custom_62_op' => 'in',
          'custom_62_value' => [],
          'custom_11_min' => '',
          'custom_11_max' => '',
          'custom_11_op' => 'lte',
          'custom_11_value' => '',
          'custom_57_relative' => '',
          'custom_57_from' => '',
          'custom_57_to' => '',
          'custom_14_relative' => 'nnll',
          'custom_14_from' => '',
          'custom_14_to' => '',
          'custom_15_relative' => '',
          'custom_15_from' => '',
          'custom_15_to' => '',
          'custom_16_op' => 'mhas',
          'custom_16_value' => [],
          'custom_58_op' => 'eq',
          'custom_58_value' => '',
          'custom_78_op' => 'eq',
          'custom_78_value' => '',
          'custom_79_op' => 'eq',
          'custom_79_value' => '',
          'custom_80_op' => 'eq',
          'custom_80_value' => '',
          'custom_81_op' => 'eq',
          'custom_81_value' => '',
          'custom_43_op' => 'in',
          'custom_43_value' => [],
          'custom_54_op' => 'eq',
          'custom_54_value' => '',
          'custom_91_op' => 'eq',
          'custom_91_value' => '',
          'custom_92_op' => 'eq',
          'custom_92_value' => '',
          'custom_93_op' => 'eq',
          'custom_93_value' => '',
          'custom_94_op' => 'eq',
          'custom_94_value' => '',
          'custom_95_op' => 'eq',
          'custom_95_value' => '',
          'custom_96_op' => 'eq',
          'custom_96_value' => '',
          'custom_97_op' => 'eq',
          'custom_97_value' => '',
          'custom_98_op' => 'eq',
          'custom_98_value' => '',
          'custom_99_op' => 'eq',
          'custom_99_value' => '',
          'custom_101_op' => 'in',
          'custom_101_value' => [],
          'custom_119_op' => 'eq',
          'custom_119_value' => '',
          'custom_110_op' => 'in',
          'custom_110_value' => [],
          'custom_109_op' => 'in',
          'custom_109_value' => [],
          'custom_111_op' => 'in',
          'custom_111_value' => [],
          'custom_112_op' => 'in',
          'custom_112_value' => [],
          'custom_113_op' => 'in',
          'custom_113_value' => [],
          'order_bys' => [
            '1' => [
              'column' => 'sort_name',
              'order' => 'ASC',
            ],
          ],
          'description' => '',
          'email_subject' => '',
          'email_to' => '',
          'email_cc' => '',
          'row_count' => '',
          'is_navigation' => '1',
          'view_mode' => 'view',
          'cache_minutes' => '60',
          'is_reserved' => '',
          'permission' => 'view all contacts',
          'parent_id' => '239',
          'radio_ts' => '',
          'groups' => '',
          'instance_id' => '36',
          'navigation' => [],
        ],
        'header' => "<html>\r\n  <head>\r\n    <title>CiviCRM Report</title>\r\n    <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />\r\n    <style type=\"text/css\">@import url(https://bia1.mainstreetrm.com/sites/bia1.mainstreetrm.com/wp-content/plugins/civicrm/civicrm/css/print.css);</style>\r\n    \r\n  </head>\r\n  <body><div id=\"crm-container\">",
        'footer' => '<p><img src="https://bia1.mainstreetrm.com/sites/bia1.mainstreetrm.com/wp-content/plugins/civicrm/civicrm/i/powered_by.png" /></p></div></body>
</html>
',
        'navigation_id.name' => 'Business Anniversary report',
      ],
    ],
  ],
];
