-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_tsr_group_refs`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_tsr_group_refs
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_tsr_group_refs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique TsrGroupRefs ID',
  `original_custom_group` int unsigned COMMENT 'FK to Custom Group',
  `tsr_custom_group` int unsigned COMMENT 'FK to Custom Group',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_tsr_group_refs_original_custom_group FOREIGN KEY (`original_custom_group`) REFERENCES `civicrm_custom_group`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_tsr_group_refs_tsr_custom_group FOREIGN KEY (`tsr_custom_group`) REFERENCES `civicrm_custom_group`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
