-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_property_unit`;
DROP TABLE IF EXISTS `civicrm_unit_business`;
DROP TABLE IF EXISTS `civicrm_unit`;
DROP TABLE IF EXISTS `civicrm_property_owner`;
DROP TABLE IF EXISTS `civicrm_property`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_property
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_property` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Property ID',
  `roll_no` varchar(255) NULL COMMENT 'Roll #',
  `created_id` int unsigned COMMENT 'FK to Contact',
  `address_id` int unsigned COMMENT 'FK to Address',
  `modified_id` int unsigned COMMENT 'FK to Contact',
  `modified_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When was the property was created or modified or deleted.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_address_id`(address_id),
  CONSTRAINT FK_civicrm_property_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_property_address_id FOREIGN KEY (`address_id`) REFERENCES `civicrm_address`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_property_modified_id FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_property_owner
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_property_owner` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique PropertyOwner ID',
  `property_id` int unsigned COMMENT 'FK to Property',
  `owner_id` int unsigned COMMENT 'FK to Contact',
  `is_voter` int unsigned COMMENT 'Is Vote?',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_property_owner_key`(property_id, owner_id),
  CONSTRAINT FK_civicrm_property_owner_property_id FOREIGN KEY (`property_id`) REFERENCES `civicrm_property`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_property_owner_owner_id FOREIGN KEY (`owner_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_unit
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_unit` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Unit ID',
  `unit_no` varchar(128) unsigned NULL COMMENT 'Unit #',
  `unit_size` decimal NULL COMMENT 'Unit Size',
  `unit_price` decimal NULL COMMENT 'Unit Price',
  `unit_status` int unsigned NULL COMMENT 'Unit Status',
  `mls_listing_link` varchar(255) NULL COMMENT 'Unit Status',
  `unit_photo` int unsigned NULL COMMENT 'Unit Photo',
  `unit_location` varchar(255) NULL COMMENT 'Unit Location',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_unit_unit_status FOREIGN KEY (`unit_status`) REFERENCES `civicrm_option_value`(`id`),
  CONSTRAINT FK_civicrm_unit_unit_photo FOREIGN KEY (`unit_photo`) REFERENCES `civicrm_file`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_unit_business
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_unit_business` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique UnitBusiness ID',
  `unit_id` int unsigned COMMENT 'FK to Unit',
  `business_id` int unsigned COMMENT 'FK to Contact',
  `property_id` int unsigned COMMENT 'FK to Unit',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_business_id`(business_id),
  UNIQUE INDEX `UI_property_unit_key`(property_id, unit_id),
  CONSTRAINT FK_civicrm_unit_business_unit_id FOREIGN KEY (`unit_id`) REFERENCES `civicrm_unit`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_unit_business_business_id FOREIGN KEY (`business_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_unit_business_property_id FOREIGN KEY (`property_id`) REFERENCES `civicrm_property`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_property_unit
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_property_unit` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique PropertyUnit ID',
  `property_id` int unsigned COMMENT 'FK to Property',
  `unit_id` int unsigned COMMENT 'FK to Unit',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_property_id_unnit_id`(property_id, unit_id),
  CONSTRAINT FK_civicrm_property_unit_property_id FOREIGN KEY (`property_id`) REFERENCES `civicrm_property`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_property_unit_unit_id FOREIGN KEY (`unit_id`) REFERENCES `civicrm_unit`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
