<?php

use Civi\Test\HeadlessInterface;
use Civi\Test\HookInterface;
use Civi\Test\TransactionalInterface;
use Civi\Api4\Contact;

/**
 * BusinessImport.Create API Test Case
 * This is a generic test class implemented with PHPUnit.
 * @group headless
 */
class api_v3_BusinessImport_CreateTest extends \PHPUnit\Framework\TestCase implements HeadlessInterface, HookInterface, TransactionalInterface {
  use \Civi\Test\Api3TestTrait;
  use \Civi\Test\ContactTestTrait;

  /**
   * Set up for headless tests.
   *
   * Civi\Test has many helpers, like install(), uninstall(), sql(), and sqlFile().
   *
   * See: https://docs.civicrm.org/dev/en/latest/testing/phpunit/#civitest
   */
  public function setUpHeadless() {
    return \Civi\Test::headless()
      ->install('biaproperty')
      ->installMe(__DIR__)
      ->apply();
  }

  /**
   * The setup() method is executed before the test is executed (optional).
   */
  public function setUp(): void {
    $this->createLoggedInUser();
    $this->propertyNumber = rand();
    $params = [
      'roll_no' => rand(),
      'property_name' => 'Jackson Square Mall',
      'property_address' => $this->propertyNumber . ' King St W',
      'city' => 'Hamilton',
      'postal_code' => 'L8P 1A1',
      'owner_1_first_name' => 'Business Import',
      'owner_1_last_name' => 'Owner',
      'owner_1_street_address' => '83 Grandview Avenue',
      'owner_1_supplemental_address_1' => 'C/0 Joe Murray',
      'owner_1_city' => 'Toronto',
      'owner_1_province' => 'ON',
      'owner_1_postal_code' => 'H0H 0H0',
      'owner_1_country' => 'Canada',
      'property_manager_first_name' => 'Business Import Manager',
      'property_manager_last_name' => 'lee',
      'property_manager_email' => 'edsel.lopez+testproperty' . rand() . '@jmaconsulting.biz',
    ];
    $this->callAPISuccess('PropertyOwnerImport', 'create', $params);
    $this->createBusinessContactType();
    $this->createCustomFields();
    parent::setUp();
  }

  /**
   * The tearDown() method is executed after the test was executed (optional)
   * This can be used for cleanup.
   */
  public function tearDown(): void {
    parent::tearDown();
  }

  private function createBusinessContactType(): void {
    $check = $this->callAPISuccess('ContactType', 'get', [
      'name' => 'Members_Businesses_',
    ]);
    if (!$check['count']) {
      $this->callAPISuccess('ContactType', 'create', [
        'label' => 'Business (member)',
        'name' => 'Members_Businesses_',
        'parent_id' => 'Organization',
      ]);
    }
  }

  private function createCustomFields(): void {
    $unitStatusCheck = $this->callAPISuccess('OptionGroup', 'get', [
      'name' => 'unit_status',
    ]);
    if (!$unitStatusCheck['count']) {
      $this->callAPISuccess('OptionGroup', 'create', [
        'version' => 4,
        'name' => 'unit_status',
        'title' => 'Unit Status',
        'description' => NULL,
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'is_locked' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ]);
      $unitStatusOptionValues = [
        [
          'version' => 4,
          'option_group_id:name' => 'unit_status',
          'label' => 'Occupied',
          'value' => '1',
          'name' => 'Occupied',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'weight' => 1,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        [
          'version' => 4,
          'option_group_id:name' => 'unit_status',
          'label' => 'Vacant (available to rent)',
          'value' => '2',
          'name' => 'Vacant_Ready_to_Rent',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'weight' => 2,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        [
          'version' => 4,
          'option_group_id:name' => 'unit_status',
          'label' => 'Vacant (under development)',
          'value' => '3',
          'name' => 'Vacant_Under_Development',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'weight' => 3,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        [
          'version' => 4,
          'option_group_id:name' => 'unit_status',
          'label' => 'Vacant (unavailable for rent and/or derelict)',
          'value' => '4',
          'name' => 'Vacant_Unavailable',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'weight' => 4,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        [
          'version' => 4,
          'option_group_id:name' => 'unit_status',
          'label' => 'Contravening bylaw (e.g. commercial used for residential uses)',
          'value' => '5',
          'name' => 'Contravening_bylaw_e_g_commerci',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'weight' => 5,
          'description' => '',
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
      ];
      foreach ($unitStatusOptionValues as $unitStatusOptionValue) {
        $this->callAPISuccess('OptionValue', 'create', $unitStatusOptionValue);
      }
      $optionGroups = [
        [
          'name' => 'Business_Category_Parent_Class',
          'title' => 'Business Category :: Parent Class',
          'description' => NULL,
          'data_type' => 'String',
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'is_locked' => FALSE,
          'option_value_fields' => [
            'name',
            'label',
            'description',
          ],
        ],
        [
          'name' => 'Business_Category_Child_Class',
          'title' => 'Business Category :: Child Class',
          'description' => NULL,
          'data_type' => 'String',
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'is_locked' => FALSE,
          'option_value_fields' => [
            'name',
            'label',
            'description',
          ],
        ],
        [
          'name' => 'Business_Category_Child_Class_Unique',
          'title' => 'Business Category :: Child Class - Unique',
          'description' => NULL,
          'data_type' => 'String',
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'is_locked' => FALSE,
          'option_value_fields' => [
            'name',
            'label',
            'description',
          ],
        ],
      ];
      $customGroups = [
        [
          'name' => 'Social_Media',
          'title' => 'Social Media',
          'extends' => 'Contact',
          'extends_entity_column_id' => NULL,
          'extends_entity_column_value' => NULL,
          'style' => 'Inline',
          'collapse_display' => FALSE,
          'help_pre' => '',
          'help_post' => '',
          'weight' => 8,
          'is_active' => TRUE,
          'table_name' => 'civicrm_value_social_media_9',
          'is_multiple' => FALSE,
          'min_multiple' => NULL,
          'max_multiple' => NULL,
          'collapse_adv_display' => TRUE,
          'is_reserved' => FALSE,
          'is_public' => TRUE,
          'icon' => '',
        ],
        [
          'name' => 'Business_Category',
          'title' => 'Category',
          'extends' => 'Organization',
          'extends_entity_column_id' => NULL,
          'extends_entity_column_value' => [
            'Members_Businesses_',
          ],
          'style' => 'Inline',
          'collapse_display' => FALSE,
          'help_pre' => '',
          'help_post' => '',
          'weight' => 11,
          'is_active' => TRUE,
          'table_name' => 'civicrm_value_business_cate_4',
          'is_multiple' => FALSE,
          'min_multiple' => NULL,
          'max_multiple' => NULL,
          'collapse_adv_display' => TRUE,
          'is_reserved' => FALSE,
          'is_public' => TRUE,
          'icon' => '',
        ],
        [
          'name' => 'Ownership_Demographics',
          'title' => 'Ownership Demographics',
          'extends' => 'Organization',
          'extends_entity_column_id' => NULL,
          'extends_entity_column_value' => NULL,
          'style' => 'Inline',
          'collapse_display' => FALSE,
          'help_pre' => '<p>Check all that apply</p>',
          'help_post' => '',
          'weight' => 17,
          'is_active' => TRUE,
          'table_name' => 'civicrm_value_ownership_dem_25',
          'is_multiple' => FALSE,
          'min_multiple' => NULL,
          'max_multiple' => NULL,
          'collapse_adv_display' => TRUE,
          'is_reserved' => FALSE,
          'is_public' => TRUE,
          'icon' => '',
        ],
      ];
      $customFields = [
       [
          'custom_group_id:name' => 'Business_Category',
          'name' => 'Parent_Class',
          'label' => 'Business Category',
          'data_type' => 'String',
          'html_type' => 'Select',
          'default_value' => NULL,
          'is_required' => TRUE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 35,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'parent_class_7',
          'option_group_id:name' => 'Business_Category_Parent_Class',
          'serialize' => 1,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Business_Category',
          'name' => 'Child_Class',
          'label' => 'Business Subcategory',
          'data_type' => 'String',
          'html_type' => 'Select',
          'default_value' => NULL,
          'is_required' => TRUE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 48,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'child_class_8',
          'option_group_id:name' => 'Business_Category_Child_Class',
          'serialize' => 1,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Business_Category',
          'name' => 'Child_Class_Unique',
          'label' => 'Local BIA Headings',
          'data_type' => 'String',
          'html_type' => 'Select',
          'default_value' => 'Dine',
          'is_required' => TRUE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 57,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'child_class_unique_9',
          'option_group_id:name' => 'Business_Category_Child_Class_Unique',
          'serialize' => 1,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Social_Media',
          'name' => 'LinkedIn',
          'label' => 'LinkedIn',
          'data_type' => 'Link',
          'html_type' => 'Link',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 1,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'linkedin_31',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Social_Media',
          'name' => 'Twitter',
          'label' => 'Twitter',
          'data_type' => 'Link',
          'html_type' => 'Link',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 30,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'twitter_35',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Social_Media',
          'name' => 'Facebook',
          'label' => 'Facebook',
          'data_type' => 'Link',
          'html_type' => 'Link',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 32,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'facebook_36',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Social_Media',
          'name' => 'Instagram',
          'label' => 'Instagram',
          'data_type' => 'Link',
          'html_type' => 'Link',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 33,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'instagram_37',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Social_Media',
          'name' => 'TikTok',
          'label' => 'TikTok',
          'data_type' => 'Link',
          'html_type' => 'Link',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => FALSE,
          'is_search_range' => FALSE,
          'weight' => 36,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'tiktok_41',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Social_Media',
          'name' => 'Google_Business_Profile',
          'label' => 'Google Maps link',
          'data_type' => 'Link',
          'html_type' => 'Link',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => FALSE,
          'is_search_range' => FALSE,
          'weight' => 34,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'google_business_profile_42',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'Francophone',
          'label' => 'Francophone',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 2,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'francophone_91',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'Women',
          'label' => 'Women',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 4,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'women_92',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'Youth_39_and_under_',
          'label' => 'Youth (39 and under)',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 6,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'youth_39_and_under__93',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'Lesbian_gay_bisexual_transsexual_queer_LGBTQ_',
          'label' => 'Lesbian, gay, bisexual, transsexual, queer (LGBTQ+)',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 8,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'lesbian_gay_bisexual_transsexual_94',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'Indigenous_First_Nations_Inuit_or_Metis_',
          'label' => 'Indigenous (First Nations, Inuit or Metis)',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 10,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'indigenous_first_nations_inuit_o_95',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'Racialized_group_member',
          'label' => 'Racialized group member',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 12,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'racialized_group_member_96',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'Newcomers_immigrants_and_refugees',
          'label' => 'Newcomers, immigrants and refugees',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 14,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'newcomers_immigrants_and_refugee_97',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'Black_community_member',
          'label' => 'Black community member',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 15,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'black_community_member_98',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
       ],
       [
          'custom_group_id:name' => 'Ownership_Demographics',
          'name' => 'People_with_disabilities',
          'label' => 'People with disabilities',
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => NULL,
          'is_required' => FALSE,
          'is_searchable' => TRUE,
          'is_search_range' => FALSE,
          'weight' => 17,
          'help_pre' => NULL,
          'help_post' => NULL,
          'mask' => NULL,
          'attributes' => NULL,
          'javascript' => NULL,
          'is_active' => TRUE,
          'is_view' => FALSE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'people_with_disabilities_99',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
        ],
      ];
      foreach ($optionGroups as $optionGroup) {
        $this->callAPISuccess('OptionGroup', 'create', array_merge(['version' => 4], $optionGroup));
      }
      foreach ($customGroups as $customGroup) {
        $this->callAPISuccess('CustomGroup', 'create', array_merge(['version' => 4], $customGroup));
      }
      foreach ($customFields as $customField) {
        $this->callAPISuccess('CustomField', 'create', array_merge(['version' => 4], $customField));
      }
      $this->callAPISuccess('OptionValue', 'create', [
        'version' => 4,
        'option_group_id:name' => 'Business_Category_Parent_Class',
        'label' => 'Arts, Entertainment and Recreation',
        'value' => '5',
        'name' => 'Arts_Entertainment_and_Recreati',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 1,
        'description' => '',
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
        'icon' => NULL,
        'color' => NULL,
      ]);
      $this->callAPISuccess('OptionValue', 'create', [
        'version' => 4,
        'option_group_id:name' => 'Business_Category_Child_Class',
        'label' => 'Event Centre',
        'value' => '3',
        'name' => 'Event_Centre',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'weight' => 7,
        'description' => '',
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
        'icon' => NULL,
        'color' => NULL,
      ]);
    }
  }

  /**
   * Simple example test case.
   *
   * Note how the function name begins with the word "test".
   */
  public function testBusinessImport() {
    $importParams = [
      'property_address' => $this->propertyNumber . ' King St W',
      'property_street_address' => $this->propertyNumber . 'King St',
      'property_tax_roll_unit' => $this->propertyNumber . 'King St W #7',
      'property_unit' => '#7',
      'unit_size' => '80.50',
      'unit_price' => '150.50',
      'unit_status' => 'Occupied',
      'unit_location' => 'Floor #2',
      'organization_name' => 'Test Business Import Org',
      'first_name' => 'Seamus',
      'last_name' => 'Lopez',
      'contact_position' => 'Manager',
      'phone' => '555 051 5155',
      'contact_email' => 'manager@testbusiness.org',
      'website' => 'https://testbusiness.test',
      'email' => 'info@testbusiness.org',
      'facebook_url' => 'https://facebook.com/testbusiness',
      'linkedin_url' => 'https://linkedIn.com/xxx',
      'twitter_url' => 'https://twitter.com/testbusiness',
      'category' => 'Arts, Entertainment and Recreation',
      'sub_category' => 'Event Centre',
      'local_bia' => 'Test Heading',
      'francophone' => FALSE,
      'women' => TRUE,
      'lgbtiq' => FALSE,
    ];
    $result = $this->callAPISuccess('BusinessImport', 'create', $importParams);
    $businessContact = $this->callAPISuccess('Contact', 'getsingle', ['organization_name' => 'Test Business Import Org']);
    $this->assertEquals('Members_Businesses_', $businessContact['contact_sub_type'][0]);
    $unit = $this->callAPISuccess('Unit', 'get', ['unit_size' => '80.50', 'version' => 4]);
    $unitId = key($unit['values']);
    $unitRecord = $unit['values'][$unitId];
    $addressRecord = $this->callAPISuccess('Address', 'get', ['id' => $unitRecord['address_id']])['values'][$unitRecord['address_id']];
    $this->assertEquals('#7', $addressRecord['street_unit']);
    $this->assertEquals($this->propertyNumber . 'King St', $addressRecord['street_address']);
    $propertyRecord = $this->callAPISuccess('Property', 'get', ['id' => $unitRecord['property_id'], 'version' => 4])['values'][$unitRecord['property_id']];
    $this->assertEquals($this->propertyNumber . ' King St W', $propertyRecord['property_address']);
    $this->assertEquals('150.50', $unitRecord['unit_price']);
    $this->assertEquals(1, $unitRecord['unit_status']);
    $this->assertEquals('Floor #2', $unitRecord['unit_location']);
    $contact = Contact::get(FALSE)->addSelect('custom.*')->addWhere('id', '=', $businessContact['id'])->execute()->first();
    $this->assertEquals('https://facebook.com/testbusiness', $contact['Social_Media.Facebook']);
    $this->assertEquals('https://linkedIn.com/xxx', $contact['Social_Media.LinkedIn']);
    $this->assertEquals('https://twitter.com/testbusiness', $contact['Social_Media.Twitter']);
    $this->assertCount(1, $this->callAPISuccess('Website', 'get', ['contact_id' => $businessContact['id'], 'url' => 'https://testbusiness.test'])['values']);
    $this->assertEquals('info@testbusiness.org', $this->callAPISuccess('Email', 'getsingle', ['contact_id' => $businessContact['id']])['email']);
    $this->assertEquals('Arts, Entertainment and Recreation', $contact['Business_Category.Parent_Class'][0]);
    $this->assertEquals('Event Centre', $contact['Business_Category.Child_Class'][0]);
    $this->assertEquals('Test Heading', $contact['Business_Category.Child_Class_Unique'][0]);
    $this->assertEquals(FALSE, $contact['Ownership_Demographics.Francophone']);
    $this->assertEquals(TRUE, $contact['Ownership_Demographics.Women']);
    $this->assertEquals(FALSE, $contact['Ownership_Demographics.Lesbian_gay_bisexual_transsexual_queer_LGBTQ_']);
    $relationship = $this->callAPISuccess('Relationship', 'getsingle', ['contact_id_b' => $businessContact['id']]);
    $this->assertEquals('555 051 5155', $this->callAPISuccess('Phone', 'getsingle', ['contact_id' => $relationship['contact_id_a']])['phone']);
    $this->assertEquals('Seamus', $this->callAPISuccess('Contact', 'getsingle', ['id' => $relationship['contact_id_a']])['first_name']);
  }


}
