-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_property_log`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_property_log
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_property_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique PropertyLog ID',
  `property_id` int unsigned NOT NULL COMMENT 'Unique Property ID',
  `is_synced` tinyint NOT NULL DEFAULT 0 COMMENT 'Has property been synced?',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_property_log_property_id FOREIGN KEY (`property_id`) REFERENCES `civicrm_property`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
