-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_civicrm_property_log`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_civicrm_property_log
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_civicrm_property_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CivicrmPropertyLog ID',
  `property_id` int unsigned COMMENT 'Unique Property ID',
  `modified_date` date COMMENT 'When the property was last modified.',
  `is_synced` tinyint DEFAULT 0 COMMENT 'Has property been synced?',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

INSERT INTO `civicrm_civicrm_property_log` (`property_id`) 
SELECT `id` FROM  `civicrm_property`;