<?php

use CRM_Biasync_ExtensionUtil as E;
return [
    [
      'name' => 'CustomGroup_Is_Synced_',
      'entity' => 'CustomGroup',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'Is_Synced_',
          'title' => E::ts('Is Synced?'),
          'extends' => 'Contact',
          'extends_entity_column_id' => NULL,
          'extends_entity_column_value' => NULL,
          'style' => 'Tab',
          'collapse_display' => FALSE,
          'help_pre' => '',
          'help_post' => '',
          'weight' => 19,
          'is_active' => TRUE,
          'is_multiple' => FALSE,
          'min_multiple' => NULL,
          'max_multiple' => NULL,
          'collapse_adv_display' => TRUE,
          'created_date' => '2023-11-01 10:00:34',
          'is_reserved' => FALSE,
          'is_public' => FALSE,
          'icon' => '',
        ],
        'match' => [
          'name',
        ],
      ],
    ],
    [
      'name' => 'CustomGroup_Is_Synced_CustomField_is_synced',
      'entity' => 'CustomField',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'custom_group_id.name' => 'Is_Synced_',
          'name' => 'is_synced',
          'label' => E::ts('is_synced'),
          'data_type' => 'Boolean',
          'html_type' => 'Radio',
          'default_value' => '0',
          'is_required' => FALSE,
          'is_searchable' => FALSE,
          'is_search_range' => FALSE,
          'help_pre' => NULL,
          'help_post' => NULL,
          'attributes' => NULL,
          'is_active' => TRUE,
          'is_view' => TRUE,
          'options_per_line' => NULL,
          'text_length' => 255,
          'start_date_years' => NULL,
          'end_date_years' => NULL,
          'date_format' => NULL,
          'time_format' => NULL,
          'note_columns' => 60,
          'note_rows' => 4,
          'column_name' => 'is_synced_111',
          'option_group_id' => NULL,
          'serialize' => 0,
          'filter' => NULL,
          'in_selector' => FALSE,
          'fk_entity' => NULL,
        ],
        'match' => [
          'name',
          'custom_group_id',
        ],
      ],
    ],
];