<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from biaproperty/xml/schema/CRM/Biaproperty/UnitBusiness.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:e99c4094b339395a262d2d7f290a562e)
 */
use CRM_Biaproperty_ExtensionUtil as E;

/**
 * Database access object for the UnitBusiness entity.
 */
class CRM_Biaproperty_DAO_UnitBusiness extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_unit_business';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique UnitBusiness ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Unit
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_id;

  /**
   * FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $business_id;

  /**
   * FK to Unit
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $property_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_unit_business';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Unit Businesses') : E::ts('Unit Business');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'unit_id', 'civicrm_unit', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'business_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'property_id', 'civicrm_property', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique UnitBusiness ID'),
          'required' => TRUE,
          'where' => 'civicrm_unit_business.id',
          'table_name' => 'civicrm_unit_business',
          'entity' => 'UnitBusiness',
          'bao' => 'CRM_Biaproperty_DAO_UnitBusiness',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'unit_id' => [
          'name' => 'unit_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Unit'),
          'where' => 'civicrm_unit_business.unit_id',
          'table_name' => 'civicrm_unit_business',
          'entity' => 'UnitBusiness',
          'bao' => 'CRM_Biaproperty_DAO_UnitBusiness',
          'localizable' => 0,
          'FKClassName' => 'CRM_Biaproperty_DAO_Unit',
          'add' => NULL,
        ],
        'business_id' => [
          'name' => 'business_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact'),
          'where' => 'civicrm_unit_business.business_id',
          'table_name' => 'civicrm_unit_business',
          'entity' => 'UnitBusiness',
          'bao' => 'CRM_Biaproperty_DAO_UnitBusiness',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'property_id' => [
          'name' => 'property_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Unit'),
          'where' => 'civicrm_unit_business.property_id',
          'table_name' => 'civicrm_unit_business',
          'entity' => 'UnitBusiness',
          'bao' => 'CRM_Biaproperty_DAO_UnitBusiness',
          'localizable' => 0,
          'FKClassName' => 'CRM_Biaproperty_DAO_Property',
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'unit_business', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'unit_business', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_business_id' => [
        'name' => 'UI_business_id',
        'field' => [
          0 => 'business_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_unit_business::1::business_id',
      ],
      'UI_property_unit_key' => [
        'name' => 'UI_property_unit_key',
        'field' => [
          0 => 'property_id',
          1 => 'unit_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_unit_business::1::property_id::unit_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
