<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from biaproperty/xml/schema/CRM/Biaproperty/Unit.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:ba9c39d0006a294bd10f1a67726403ec)
 */
use CRM_Biaproperty_ExtensionUtil as E;

/**
 * Database access object for the Unit entity.
 */
class CRM_Biaproperty_DAO_Unit extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_unit';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Unit ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Unit #
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_no;

  /**
   * Unit Size
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_size;

  /**
   * Unit Price
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_price;

  /**
   * Unit Status
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_status;

  /**
   * Unit Status
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $mls_listing_link;

  /**
   * Unit Photo
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_photo;

  /**
   * Unit Location
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_location;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_unit';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Units') : E::ts('Unit');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'unit_status', 'civicrm_option_value', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'unit_photo', 'civicrm_file', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Unit ID'),
          'required' => TRUE,
          'where' => 'civicrm_unit.id',
          'table_name' => 'civicrm_unit',
          'entity' => 'Unit',
          'bao' => 'CRM_Biaproperty_DAO_Unit',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'unit_no' => [
          'name' => 'unit_no',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Unit No'),
          'description' => E::ts('Unit #'),
          'required' => FALSE,
          'where' => 'civicrm_unit.unit_no',
          'table_name' => 'civicrm_unit',
          'entity' => 'Unit',
          'maxlength' => 128,
          'bao' => 'CRM_Biaproperty_DAO_Unit',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'unit_size' => [
          'name' => 'unit_size',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Unit Size'),
          'description' => E::ts('Unit Size'),
          'required' => FALSE,
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicrm_unit.unit_size',
          'table_name' => 'civicrm_unit',
          'entity' => 'Unit',
          'bao' => 'CRM_Biaproperty_DAO_Unit',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'unit_price' => [
          'name' => 'unit_price',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Unit Price'),
          'description' => E::ts('Unit Price'),
          'required' => FALSE,
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicrm_unit.unit_price',
          'table_name' => 'civicrm_unit',
          'entity' => 'Unit',
          'bao' => 'CRM_Biaproperty_DAO_Unit',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'unit_status' => [
          'name' => 'unit_status',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Unit Status'),
          'description' => E::ts('Unit Status'),
          'required' => FALSE,
          'where' => 'civicrm_unit.unit_status',
          'table_name' => 'civicrm_unit',
          'entity' => 'Unit',
          'bao' => 'CRM_Biaproperty_DAO_Unit',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_OptionValue',
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'unit_status',
            'optionEditPath' => 'civicrm/admin/options/unit_status',
          ],
          'add' => NULL,
        ],
        'mls_listing_link' => [
          'name' => 'mls_listing_link',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Mls Listing Link'),
          'description' => E::ts('Unit Status'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_unit.mls_listing_link',
          'table_name' => 'civicrm_unit',
          'entity' => 'Unit',
          'bao' => 'CRM_Biaproperty_DAO_Unit',
          'localizable' => 0,
          'html' => [
            'type' => 'Url',
          ],
          'add' => NULL,
        ],
        'unit_photo' => [
          'name' => 'unit_photo',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Unit Photo'),
          'description' => E::ts('Unit Photo'),
          'required' => FALSE,
          'where' => 'civicrm_unit.unit_photo',
          'table_name' => 'civicrm_unit',
          'entity' => 'Unit',
          'bao' => 'CRM_Biaproperty_DAO_Unit',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_File',
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'unit_location' => [
          'name' => 'unit_location',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Unit Location'),
          'description' => E::ts('Unit Location'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_unit.unit_location',
          'table_name' => 'civicrm_unit',
          'entity' => 'Unit',
          'bao' => 'CRM_Biaproperty_DAO_Unit',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'unit', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'unit', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
