<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from biasync/xml/schema/CRM/Biasync/CivicrmPropertyLog.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:537d3bf11aee7b4b08282ae84c33f006)
 */
use CRM_Biasync_ExtensionUtil as E;

/**
 * Database access object for the CivicrmPropertyLog entity.
 */
class CRM_Biasync_DAO_CivicrmPropertyLog extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_civicrm_property_log';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CivicrmPropertyLog ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Property ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $property_id;

  /**
   * When was the property was created or modified or deleted.
   *
   * @var string
   *   (SQL type: date)
   *   Note that values will be retrieved from the database as a string.
   */
  public $modified_date;

  /**
   * When was the property was created or modified or deleted.
   *
   * @var boolean
   *   (SQL type: boolean)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_synced;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_civicrm_property_log';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Civicrm Property Logs') : E::ts('Civicrm Property Log');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique CivicrmPropertyLog ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_civicrm_property_log.id',
          'table_name' => 'civicrm_civicrm_property_log',
          'entity' => 'CivicrmPropertyLog',
          'bao' => 'CRM_Biasync_DAO_CivicrmPropertyLog',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'property_id' => [
          'name' => 'property_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Property} ID'),
          'description' => E::ts('Property ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_civicrm_property_log.property_id',
          'table_name' => 'civicrm_civicrm_property_log',
          'entity' => 'CivicrmPropertyLog',
          'bao' => 'CRM_Biasync_DAO_CivicrmPropertyLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => E::ts('Modified Date'),
          'description' => E::ts('When was the property was created or modified or deleted.'),
          'required' => FALSE,
          'where' => 'civicrm_civicrm_property_log.modified_date',
          'default' => 'CURRENT_DATE ON UPDATE CURRENT_DATE',
          'table_name' => 'civicrm_civicrm_property_log',
          'entity' => 'CivicrmPropertyLog',
          'bao' => 'CRM_Biasync_DAO_CivicrmPropertyLog',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Modified Date"),
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'is_synced' => [
          'name' => 'is_synced',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Synced?'),
          'description' => E::ts('Property ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_civicrm_property_log.is_synced',
          'table_name' => 'civicrm_civicrm_property_log',
          'entity' => 'CivicrmPropertyLog',
          'bao' => 'CRM_Biasync_DAO_CivicrmPropertyLog',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'civicrm_property_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'civicrm_property_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
